### ISSUE TITLE
Browser icon missing

### ISSUE THREAD

**Issue by clickervolt** [matomo-org/matomo-icons#21]
Hi

It looks like `LieBaoFast` browser doesn't have an existing icon:

https://devicedetector.lw1.at/Mozilla%2F5.0(Linux;Android%205.1.1;OPPO%20A33%20Build%2FLMY47V;wv)%20AppleWebKit%2F537.36(KHTML,link%20Gecko)%20Version%2F4.0%20Chrome%2F43.0.2357.121%20Mobile%20Safari%2F537.36%20LieBaoFast%2F4.51.3

`
"clientInfo": {
    "type": "browser",
    "name": "LieBaoFast",
    "short_name": "LF",
    "version": "4.51.3",
    "engine": "WebKit",
    "engine_version": "537.36"
},`

`LF.png` isn't there in the browsers folder.

**Comment by Findus23** [comment]
Hi,

You are right and as I see the icon is on my list of icons that are "intentionally" missing.

https://github.com/matomo-org/matomo-icons/blob/d22c22848b3b8f19a031f396745fcaeaefb1abcd/tests-ignore.yml#L265

In this case this is because I have no idea what the icon is. A search on the internet for `LieBaoFast` doesn't give any official information.

And now that I think about it, we already had a similar discussion in https://github.com/matomo-org/device-detector/issues/6056 which resulted in noticing that Liebao is probably an old name for CM Browser (which does have an icon).

So the best solution is probably to also detect this browser as CM (see also https://github.com/matomo-org/device-detector/issues/6056#issuecomment-549294179)

**Comment by clickervolt** [comment]
Got it, thanks :)

**Comment by tsteur** [comment]
@Findus23 can we close the issue in this case?

**Comment by clickervolt** [comment]
Actually I got another user agent where the browser icon is missing, and this one is not in the ignore list.

https://devicedetector.lw1.at/Mozilla%2F5.0%20(Linux;%20Android%205.1.1;%20vivo%20X7%20Build%2FLMY47V)%20AppleWebKit%2F537.36%20(KHTML,%20like%20Gecko)%20Version%2F4.0%20Chrome%2F38.0.0.0%20Mobile%20Safari%2F537.36%20VivoBrowser%2F5.0.10

**Comment by Findus23** [comment]
@clickervolt This icon is indeed missing (see the automated test https://travis-ci.org/matomo-org/matomo-icons/jobs/607434935#L264 line 264)

This is because this browser was only added two weeks ago (https://github.com/matomo-org/device-detector/pull/6072) and I only get around to catching up with the icons once before a Matomo release.

**Comment by clickervolt** [comment]
Ah I see, nice to see you have tests for catching those! We can probably close this issue as you already have those scheduled I guess
